### ISSUE TITLE
Is there a way to avoid root access?

### ISSUE THREAD

**Issue by raitonoberu** [installer/instl#40]
Users are a little [confused](https://github.com/raitonoberu/sptlrx/issues/3) by the fact that sudo is required for installation. Is there any way to avoid requesting root access? How about placing the binary file in `~/.local/bin`?

Thanks.

**Comment by MarvinJWendt** [comment]
Hi @raitonoberu, yes this was discussed often. The alternative would be to put the binary into your path manually, but that would make the installer pretty much useless, as you could download the binary manually too then. The whole point of Instl is to make installing as easy as possible. It works on most systems and doesn't need to be installed first, so even non programmers can use it easily. Also, packages don't have to be registered, so you can even install GitHub projects using Instl, that are not even familiar of the existence of Instl.

Installing software requires root on most systems, and people can't see what those installers are doing (Windows MSI,  MacBook). Even installing `brew` on a MacBook requires sudo. Instl is open source, and you can check the code by opening the installation URL in a browser, to verify it's content, which you can't do on most other installers. 

It is a risk to run sudo in the terminal with something fetched from the internet, indeed, so I would always recommend checking the script. The best way would be to push the project to all registries, so that users can install it with their favorite package manager, but then you might have a couple users who don't use a package manager at all, or have one that isn't supported by your project. In that case, the only thing they could do is to manually install the project. And if they don't have experience with that (It's very uncommon for Windows users to install a binary manually), they won't be able to install the project at all. Instl is not meant to be used by giant projects who have dedicated teams to maintain installers and package manager registries, but for people who coded a little fun project and want to share that easily without needing any setup, and in that case, root is (sadly) the only way we can go. 

Just for reference, if you want to install `hub` by GitHub, you can see that most package managers require sudo:

![image](https://user-images.githubusercontent.com/31022056/152177270-634556e9-8d10-4693-9806-10b19861c49a.png)

**Comment by raitonoberu** [comment]
I agree with every word. Thank you for such a detailed explanation.

**Comment by fushinari** [comment]
Why not provide a fallback when not run using `sudo`? i.e. if not run with root, try to install to `~/.local/bin` if it's in `PATH`

**Comment by MarvinJWendt** [comment]
Yes, that makes sense @fushinari! I’ll add that to the tracker :)

**Comment by HadetTheUndying** [comment]
> Hi @raitonoberu, yes this was discussed often. The alternative would be to put the binary into your path manually, but that would make the installer pretty much useless, as you could download the binary manually too then. The whole point of Instl is to make installing as easy as possible. It works on most systems and doesn't need to be installed first, so even non programmers can use it easily. Also, packages don't have to be registered, so you can even install GitHub projects using Instl, that are not even familiar of the existence of Instl.
> 
> Installing software requires root on most systems, and people can't see what those installers are doing (Windows MSI, MacBook). Even installing `brew` on a MacBook requires sudo. Instl is open source, and you can check the code by opening the installation URL in a browser, to verify it's content (just a few lines of commands), which you can't do on most other installers.
> 
> It is a risk to run sudo in the terminal with something fetched from the internet, indeed, so I would always recommend checking the script. The best way would be to push the project to all registries, so that users can install it with their favorite package manager, but then you might have a couple users who don't use a package manager at all, or have one that isn't supported by your project. In that case, the only thing they could do is to manually install the project. And if they don't have experience with that (It's very uncommon for Windows users to install a binary manually), they won't be able to install the project at all. Instl is not meant to be used by giant projects who have dedicated teams to maintain installers and package manager registries, but for people who coded a little fun project and want to share that easily without needing any setup, root is (sadly) the only way we can go.
> 
> Just for reference, if you want to install `hub` by GitHub, you can see that most package managers require sudo (the ones that don't, most likely required it when they were installed to the system):
> 
> ![image](https://user-images.githubusercontent.com/31022056/152177270-634556e9-8d10-4693-9806-10b19861c49a.png)

The issue with your explanation is that it's very easy to verify package integrity and checksums with those package managers, and while you can do the same thing with `hub` that doesn't alleviate the security concerns of this installer, since most provided instructions don't tell you do verify a checksum or verify the source before download. It is entirely possible to have local user only installs with instl, and that should be the default behavior, IMO. You can have it source it's install path directly into the person's shell profile too. This is now `pip`'s default behavior and i believe gem and npm are now shifting towards this for security reasons as well. Most Linux Distributions don't encourage their users to add unverified sources to their system.*Calling out Arch and Ubuntu from PPAs here.) Being dismissive over requiring `sudo` for an unverified piece of software is very bad. I trust my distribution's maintainers to make sure the software in the repos is quality and not a security risk. I trust other people on GitHub with some niche project to be as lazy and awful at coding as I am. Do you see the difference?

**Comment by MarvinJWendt** [comment]
Hi @HadetTheUndying, #42 covers that instl will try to install locally without root in the future, but this won't work for every system. 

>  You can have it source it's install path directly into the person's shell profile too.

This was discussed previously, but people also consider manipulating the shell profile as a bad practice. There sadly isn't a way to satisfy everyone. Also, if multiple shells are installed, it would be hard to find the correct profile file. 

> It is entirely possible to have local user only installs with instl, and that should be the default behavior, IMO.

That really depends on the environment. We tested instl in its previous state on different operating systems and some did not work without sudo, as they didn't have a local binary path by default. The main purpose of instl is to provide a simple way to install any project to any machine. 

Some of the main audience are users that have zero tech-knowledge and don't work with the terminal normally (mostly windows/macOS users). For example, you're building a tool to edit all images in a folder. Now a photographer stumbles across said tool and wants to install it. The photographer is using macOS and used the terminal 3 times in his lifetime. He now wants to install your tool. Just copying and pasting a single command from the description of the project is the easiest way to install the tool. With sudo there is not much that could fail on instls side. If we don't use sudo for that, the user could get an error if he hasn't configured a local path manually, which he probably won't have, since he's not working with the terminal usually. Then he would be prompted with something that says he has to configure a local binary path by adding something to his shell file. Many casual users won't understand a single word of that and probably move on without the tool. 

That said, I don't like the usage of admin rights here too. The next step for instl will be to run it without sudo by default, and check if it can install to a local path. If that doesn't work, it will recommend the command with sudo and add a link to the instl docs, where a tutorial will be posted, how a local path can be set up to install without admin rights. I hope this solution fits the most people.

**Comment by MarvinJWendt** [comment]
Instl no longer requires root/sudo in `v1.9.0` 🎉

**Comment by raitonoberu** [comment]
Awesome!! Thanks a lot 💙
